observatory = "Alab"
location = { lon = "138.472153deg", lat = "35.940874deg", height = "1386m" }
"observation_frequency[GHz]" = 115.27120

simulator = true

alert_interval_sec = 1
record_every_n_spectral_data = 1

[ros]
service_timeout_sec = 10
communication_deadline_sec = 0.01
logging_interval_sec = 2
topic_scan_interval_sec = 1

[chopper_motor]
_ = "AZD_AD"
host = "192.168.100.145"
port = 10001
position = { insert = 20000, remove = 8000 }
low_limit = 0
high_limit = 20000

[signal_generator]
_ = "E8257D"
communicator = "LAN"
host = "192.168.100.51"
lan_port = 5025

[power_meter]
_ = "ML2437A"
host = "192.168.100.106"
port = 13

[thermometer]
_ = "Model218"
communicator = "GPIB"
port = 1
channel = { Stage4K1 = 1, Shield40K1 = 2, Shield40K2 = 3, Stage4K2 = 4 }

[weather_station]
_ = "TR73U"
port = "/dev/ttyUSB3"

[sis_bias_setter]
_ = "CPZ340816"
rsw_id = 0
channel = { USB = 3}
max_mv = [-8, 8]
converter = "x / 3"

[sis_bias_reader]
_ = "CPZ3177"
rsw_id = 0
ave_num = 100
smpl_freq = 1000
single_diff = "SINGLE"
all_ch_num = 10
ch_range = '5V'
channel = {sis_USB_V = 5, sis_USB_I = 6}
converter = [
    { ch = "sis_USB_V", V = "x * 5" },
    { ch = "sis_USB_I", I = "x * 500" },
]

[local_attenuator]
_ = "CPZ340516"
channel = { 100GHz = 1 }
range = "DA0_100mA"
rate = 0.1
rsw_id = 0

[vacuum_gauge]
_ = "TPG261"
communicator = "LAN"
host = "192.168.100.108"
port = 1001
