observatory = "NANTEN2"
location = { lon = "-67.70308139deg", lat = "-22.96995611deg", height = "4863.85m" }
"observation_frequency[GHz]" = 115.27120

simulator = true

alert_interval_sec = 1
record_every_n_spectral_data = 1

[ros]
service_timeout_sec = 10
communication_deadline_sec = 0.01
logging_interval_sec = 2
topic_scan_interval_sec = 1

[antenna]
pid_param_az = [1.5, 0.0, 0.0]
pid_param_el = [1.5, 0.0, 0.0]
drive_range_az = ["0deg", "360deg"]
drive_range_el = ["10deg", "90deg"]
drive_warning_limit_az = ["10deg", "350deg"]
drive_warning_limit_el = ["20deg", "80deg"]
drive_critical_limit_az = ["5deg", "355deg"]
drive_critical_limit_el = ["15deg", "85deg"]
"pointing_accuracy[arcsec]" = 10
pointing_parameter_path = "./pointing_param.toml"
"scan_margin[deg]" = 0.1
"max_acceleration_az[deg s-2]" = 1.6
"max_acceleration_el[deg s-2]" = 1.6
"max_speed_az[deg/s]" = 1.6
"max_speed_el[deg/s]" = 1.6
command_frequency = 50
command_offset_sec = 3

[dome]
pid_param_az = [1.5, 0.0, 0.0]
"max_acceleration_az[deg s-2]" = 1.6
"max_speed_az[deg/s]" = 1.6
command_frequency = 50
command_offset_sec = 3
"sync_accuracy[deg]" = 1
"sync_limit[deg]" = 2
drive_range_az = ["-20deg", "380deg"]
drive_warning_limit_az = ["-10deg", "370deg"]
drive_critical_limit_az = ["-15deg", "375deg"]

[chopper_motor]
_ = "CPZ7415V"
rsw_id = 0
position = { insert = 4750, remove = 19700 }

[m2_motor]
_ = "CPZ2724"
rsw_id = 1
cw = 0x10
ccw = 0x11
pulse_rate = 80
motor_speed = 200

[m4_motor]
_ = "CPZ7204"
rsw_id = 0

[antenna_motor]
_ = "CPZ2724"
rsw_id = 0
max_rate = 10000

[dome_motor]
_ = "CPZ2724"
rsw_id = 2
position = { open = [1, 1], close = [0, 1]}

[membrane_motor]
_ = "CPZ2724"
rsw_id = 2
position = { open = [1, 1], close = [0, 1]}

[drive_motor]
_ = "CPZ2724"
rsw_id = 1
drive_pos = { on = [1, 1], off = [0, 0] }
contactor_pos = { on = [1, 1, 1, 1], off = [0, 0, 0, 0] }

[antenna_encoder]
_ = "CPZ6204"
rsw_id = 0
separation = "antenna"
az_adjust = 360
el_adjust = 45

[dome_encoder]
_ = "CPZ6204"
rsw_id = 1
separation = "dome"
dome_encoffset = 10000
dome_enc1loop = 2343
dome_enc_tel_offset = 1513
dome_adjust = 360

[ccd_controller]
_ = "M100"
host = "192.168.100.47"
port = 50000
pointing_param_path = ""
pic_captured_path = "/home/pi/data/optical_pointing"

[signal_generator.115G_1st]
_ = "E8257D"
host = "172.20.0.170"
port = 5025

[signal_generator.230G_1st]
_ = "E8257D"
host = "172.20.0.171"
port = 5025

[signal_generator.115G_2nd_usb]
_ = "MG3692C"
host = "192.168.100.51"
port = 14

[signal_generator.115G_2nd_lsb]
_ = "MG3692C"
host = "192.168.100.51"
port = 14

[signal_generator.230G_2nd_usb]
_ = "MG3692C"
host = "192.168.100.51"
port = 11

[signal_generator.230G_2nd_lsb]
_ = "E8257D"
host = "192.168.100.51"
port = 5025

[thermometer]
_ = "Model218"
communicator = "GPIB"
host = "172.20.0.155"
channel = { Stage4K1 = 1, Shield40K1 = 2, Shield40K2 = 3, Stage4K2 = 4 }

[weather_station]
_ = "TR73U"
port = "/dev/ttyUSB3"

[sis_bias_setter]
_ = "CPZ340816"
rsw_id = 0
channel = { USB = 3, LSB = 4 }
max_mv = [-8, 8]
converter = "x / 3"

[sis_bias_reader]
_ = "CPZ3177"
rsw_id = 0
ave_num = 100
smpl_freq = 1000
single_diff = "SINGLE"
all_ch_num = 10
ch_range = '5V'
channel = { hemt_ch1_Vdr = 1, hemt_ch1_Vg1 = 2, hemt_ch1_Vg2 = 3, sis_USB_V = 5, sis_LSB_V = 7, sis_USB_I = 6, sis_LSB_I = 8, sis_USB_P = 9, sis_LSB_P = 10 }
converter = [
    { ch = "hemt_ch1_Vdr", V = "x" },
    { ch = "hemt_ch1_Vg1", V = "x" },
    { ch = "hemt_ch1_Vg2", V = "x" },
    { ch = "sis_USB_V", V = "x * 5" },
    { ch = "sis_USB_I", I = "x * 500" },
    { ch = "sis_LSB_V", V = "x * 5" },
    { ch = "sis_LSB_I", I = "x * 500" },
    { ch = "sis_USB_P", P = "x * 6 - 30" },
    { ch = "sis_LSB_P", P = "x * 6 - 30" },
]

[hemt_bias_reader]
_ = "CPZ3177"
rsw_id = 0

[spectrometer]
_ = "XFFTS"
host = "localhost"
data_port = 25144
cmd_port = 16210
synctime_us = 100000
bw_MHz = { 1 = 2000, 2 = 2000, 3 = 2000, 4 = 2000 }
max_ch = 32768

[attenuator.beam2]
_ = "11713B"
communicator = "GPIB"
host = "172.20.0.161"
gpib_port = 28
channel = { 2R = X, 2L = Y }

[attenuator.beam3]
_ = "11713B"
communicator = "LAN"
host = "172.20.0.164"
lan_port = 5025
channel = { 3R = X, 3L = Y }

[attenuator.beam4]
_ = "11713B"
communicator = "LAN"
host = "172.20.0.165"
lan_port = 5025
channel = { 4R = X, 4L = Y }

[attenuator.beam5]
_ = "11713B"
communicator = "LAN"
host = "172.20.0.166"
lan_port = 5025
channel = { 5R = X, 5L = Y }

[attenuator.beam1R]
_ = "11713B"
communicator = "GPIB"
host = "172.20.0.162"
gpib_port = 28
channel = { 1RU = X, 1RL = Y }

[attenuator.beam1L]
_ = "11713B"
communicator = "GPIB"
host = "172.20.0.163"
gpib_port = 28
channel = { 1LU = X, 1LL = Y }

[local_attenuator]
_ = "CPZ340516"
channel = { 100GHz = 1 }
range = "DA0_100mA"
rate = 0.1
rsw_id = 0

[vacuum_gauge]
_ = "TPG261"
communicator = "RS232"
rs232_port = ""
