[spectrometer]
if_name = { 1 = "beam115G-usb", 2 = "beam115G-lsb" , 3 = "beam115G-usb", 4 = "beam115G-lsb", 5 = "beam115G-usb", 6 = "beam115G-lsb", 7 = "beam115G-usb", 8 = "beam115G-lsb", 9 = "beam115G-usb", 10 = "beam115G-lsb", 11 = "beam115G-usb", 12 = "beam115G-lsb", 13 = "beam115G-usb", 14 = "beam115G-lsb", 15 = "beam115G-usb", 16  = "beam115G-lsb"}

[multiplier]
factor_100GHz_lo = 6
factor_200GHz_lo = 12
