observatory = "NANTEN2"
location = { lon = "-67.70308139deg", lat = "-22.96995611deg", height = "4863.85m" }
"observation_frequency[GHz]" = 115.27120

simulator = true

alert_interval_sec = 1
record_every_n_spectral_data = 1

[ros]
service_timeout_sec = 10
communication_deadline_sec = 0.01
logging_interval_sec = 2
topic_scan_interval_sec = 1

[antenna]
pid_param_az = [1.5, 0.0, 0.0]
pid_param_el = [1.5, 0.0, 0.0]
drive_range_az = ["-220deg", "268deg"]
drive_range_el = ["3deg", "85deg"]
drive_warning_limit_az = ["-195deg", "235deg"]
drive_warning_limit_el = ["15deg", "70deg"]
drive_critical_limit_az = ["-200deg", "240deg"]
drive_critical_limit_el = ["10deg", "75deg"]
"pointing_accuracy[arcsec]" = 10
pointing_parameter_path = "./pointing_param.toml"
"scan_margin[deg]" = 0.1
"max_acceleration_az[deg s-2]" = 1.6
"max_acceleration_el[deg s-2]" = 1.6
"max_speed_az[deg/s]" = 1.6
"max_speed_el[deg/s]" = 1.6
command_frequency = 50
enc_frequency = 50
command_offset_sec = 3

[dome]
pid_param_az = [1.5, 0.0, 0.0]
"max_acceleration_az[deg s-2]" = 1.6
"max_speed_az[deg/s]" = 1.6
command_frequency = 50
enc_frequency = 50
command_offset_sec = 3
"sync_accuracy[deg]" = 1
"sync_limit[deg]" = 2
drive_range_az = ["-20deg", "380deg"]
drive_warning_limit_az = ["-10deg", "370deg"]
drive_critical_limit_az = ["-15deg", "375deg"]

[chopper_motor]
_ = "CPZ7415V"
rsw_id = 0
position = { insert = 0, remove = 250 }
useaxes = "xyu"
x_mode = "jog"
y_mode = "jog"
u_mode = "ptp"
x_pulse_conf = { PULSE = 1, OUT = 0, DIR = 0, WAIT = 0, DUTY = 0 }
y_pulse_conf = { PULSE = 1, OUT = 0, DIR = 0, WAIT = 0, DUTY = 0 }
u_pulse_conf = { PULSE = 1, OUT = 1, DIR = 1, WAIT = 0, DUTY = 0 }
x_motion = { clock = 59, acc_mode = "acc_normal", low_speed = 10, speed = 5000, acc = 50, dec = 50, step = 1 }
y_motion = { clock = 59, acc_mode = "acc_normal", low_speed = 10, speed = 5000, acc = 50, dec = 50, step = 1 }
u_motion = { clock = 2999, acc_mode = "acc_normal", low_speed = 250, speed = 10000, acc = 1000, dec = 1000, step = 0 }
channel = { az = "y", el = "x", chopper = "u" }
speed_to_pulse_factor_az = -200000
speed_to_pulse_factor_el = -200000

[m2_motor]
_ = "CPZ2724"
rsw_id = 1
cw = 0x10
ccw = 0x11
pulse_rate = 80
motor_speed = 200

[m4_motor]
_ = "CPZ7204"
rsw_id = 0

[antenna_motor]
_ = "CPZ2724"
rsw_id = 0
max_rate = 10000

[dome_motor]
_ = "CPZ2724"
rsw_id = 2
position = { open = [1, 1], close = [0, 1] }

[membrane_motor]
_ = "CPZ2724"
rsw_id = 2
position = { open = [1, 1], close = [0, 1] }

[drive_motor]
_ = "CPZ2724"
rsw_id = 1
drive_pos = { on = [1, 1], off = [0, 0] }
contactor_pos = { on = [1, 1, 1, 1], off = [0, 0, 0, 0] }

[drive_status]
_ = "CPZ2724"
rsw_id = 0

[antenna_encoder]
_ = "CPZ6204"
rsw_id = 0
separation = "antenna"
az_adjust = 360
el_adjust = 45

[dome_encoder]
_ = "CPZ6204"
rsw_id = 1
separation = "dome"
dome_encoffset = 10000
dome_enc1loop = 2343
dome_enc_tel_offset = 1513
dome_adjust = 360

[ccd_controller]
_ = "M100"
host = "192.168.100.47"
port = 50000
pointing_param_path = ""
pic_captured_path = "/home/pi/data/optical_pointing"

[signal_generator.beam115G_1st]
_ = "E8257D"
host = "172.20.0.170"
port = 5025

[signal_generator.beam230G_1st]
_ = "E8257D"
host = "172.20.0.171"
port = 5025

[signal_generator.beam115G_2nd_usb]
_ = "MG3692C"
host = "172.20.0.172"
port = 14

[signal_generator.beam115G_2nd_lsb]
_ = "MG3692C"
host = "172.20.0.173"
port = 14

[signal_generator.beam230G_2nd_usb]
_ = "MG3692C"
host = "172.20.0.174"
port = 11

[signal_generator.beam230G_2nd_lsb]
_ = "E8257D"
host = "172.20.0.175"
port = 5025

[thermometer]
_ = "Model218"
communicator = "GPIB"
host = "172.20.0.155"
port = 13
channel = { ch1 = 1, ch2 = 2, ch3 = 3, ch4 = 4, ch5 = 5, ch6 = 6, ch7 = 7, ch8 = 8 }

[weather_station]
_ = "TR73U"
port = "/dev/ttyUSB3"

[sis_bias_setter.board0]
_ = "CPZ340816"
rsw_id = 0
channel = { sis_2L = 1, sis_2R = 2, sis_3L = 3, sis_3R = 4 }
max_mv = [-16, 16]
converter = "x / 3"

[sis_bias_setter.board1]
_ = "CPZ340816"
rsw_id = 1
channel = { sis_4L = 1, sis_4R = 2, sis_5L = 3, sis_5R = 4 }
max_mv = [-16, 16]
converter = "x / 3"

[sis_bias_setter.board2]
_ = "CPZ340816"
rsw_id = 2
channel = { sis_1LU = 1, sis_1LL = 2, sis_1RU = 3, sis_1RL = 4 }
max_mv = [-16, 16]
converter = "x / 3"

[sis_bias_reader]
_ = "CPZ3177"
rsw_id = 0
ave_num = 100
smpl_freq = 1000
single_diff = "DIFF"
all_ch_num = 24
ch_range = '5V' # TODO: check! in the script
channel = { sis_2L_V = 1, sis_2L_I = 2, sis_2R_V = 3, sis_2R_I = 4, sis_3L_V = 5, sis_3L_I = 6, sis_3R_V = 7, sis_3R_I = 8, sis_4L_V = 9, sis_4L_I = 10, sis_4R_V = 11, sis_4R_I = 12, sis_5L_V = 13, sis_5L_I = 14, sis_5R_V = 15, sis_5R_I = 16, sis_1LU_V = 17, sis_1LU_I = 18, sis_1LL_V = 19, sis_1LL_I = 20, sis_1RU_V = 21, sis_1RU_I = 22, sis_1RL_V = 23, sis_1RL_I = 24 }
converter = [
    { ch = "sis_2L_V", V = "x * 10" },
    { ch = "sis_2L_I", I = "x * 1000" },
    { ch = "sis_2R_V", V = "x * 10" },
    { ch = "sis_2R_I", I = "x * 1000" },
    { ch = "sis_3L_V", V = "x * 10" },
    { ch = "sis_3L_I", I = "x * 1000" },
    { ch = "sis_3R_V", V = "x * 10" },
    { ch = "sis_3R_I", I = "x * 1000" },
    { ch = "sis_4L_V", V = "x * 10" },
    { ch = "sis_4L_I", I = "x * 1000" },
    { ch = "sis_4R_V", V = "x * 10" },
    { ch = "sis_4R_I", I = "x * 1000" },
    { ch = "sis_5L_V", V = "x * 10" },
    { ch = "sis_5L_I", I = "x * 1000" },
    { ch = "sis_5R_V", V = "x * 10" },
    { ch = "sis_5R_I", I = "x * 1000" },
    { ch = "sis_1LU_V", V = "x * 10" },
    { ch = "sis_1LU_I", I = "x * 1000" },
    { ch = "sis_1LL_V", V = "x * 10" },
    { ch = "sis_1LL_I", I = "x * 1000" },
    { ch = "sis_1RU_V", V = "x * 10" },
    { ch = "sis_1RU_I", I = "x * 1000" },
    { ch = "sis_1RL_V", V = "x * 10" },
    { ch = "sis_1RL_I", I = "x * 1000" },
]

[hemt_bias_reader]
_ = "CPZ3177"
rsw_id = 1
ave_num = 100
smpl_freq = 1000
single_diff = "SINGLE"
all_ch_num = 32
ch_range = '5V' # TODO: check! in the script
channel = { hemt_2L_Vdr = 1, hemt_2L_Vg1 = 2, hemt_2L_Vg2 = 3, hemt_2L_Id = 4, hemt_2R_Vdr = 5, hemt_2R_Vg1 = 6, hemt_2R_Vg2 = 7, hemt_2R_Id = 8, hemt_3L_Vdr = 9, hemt_3L_Vg1 = 10, hemt_3L_Vg2 = 11, hemt_3L_Id = 12, hemt_3R_Vdr = 13, hemt_3R_Vg1 = 14, hemt_3R_Vg2 = 15, hemt_3R_Id = 16, hemt_4L_Vdr = 17, hemt_4L_Vg1 = 18, hemt_4L_Vg2 = 19, hemr_4L_Id = 20, hemt_4R_Vdr = 21, hemt_4R_Vg1 = 22, hemt_4R_Vg2 = 23, hemt_4R_Id = 24, hemt_5L_Vdr = 25, hemt_5L_Vg1 = 26, hemt_5L_Vg2 = 27, hemt_5L_Id = 28, hemt_5R_Vdr = 29, hemt_5R_Vg1 = 30, hemt_5R_Vg2 = 31, hemt_5R_Id = 32 }
converter = [
    { ch = "hemt_2L_Vdr", V = "x" },
    { ch = "hemt_2L_Vg1", V = "x" },
    { ch = "hemt_2L_Vg2", V = "x" },
    { ch = "hemt_2L_Id", I = "10000 * x" },
    { ch = "hemt_2R_Vdr", V = "x" },
    { ch = "hemt_2R_Vg1", V = "x" },
    { ch = "hemt_2R_Vg2", V = "x" },
    { ch = "hemt_2R_Id", I = "10000 * x" },
    { ch = "hemt_3L_Vdr", V = "x" },
    { ch = "hemt_3L_Vg1", V = "x" },
    { ch = "hemt_3L_Vg2", V = "x" },
    { ch = "hemt_3L_Id", I = "10000 * x" },
    { ch = "hemt_3R_Vdr", V = "x" },
    { ch = "hemt_3R_Vg1", V = "x" },
    { ch = "hemt_3R_Vg2", V = "x" },
    { ch = "hemt_3R_Id", I = "10000 * x" },
    { ch = "hemt_4L_Vdr", V = "x" },
    { ch = "hemt_4L_Vg1", V = "x" },
    { ch = "hemt_4L_Vg2", V = "x" },
    { ch = "hemt_4L_Id", I = "10000 * x" },
    { ch = "hemt_4R_Vdr", V = "x" },
    { ch = "hemt_4R_Vg1", V = "x" },
    { ch = "hemt_4R_Vg2", V = "x" },
    { ch = "hemt_4R_Id", I = "10000 * x" },
    { ch = "hemt_5L_Vdr", V = "x" },
    { ch = "hemt_5L_Vg1", V = "x" },
    { ch = "hemt_5L_Vg2", V = "x" },
    { ch = "hemt_5L_Id", I = "10000 * x" },
    { ch = "hemt_5R_Vdr", V = "x" },
    { ch = "hemt_5R_Vg1", V = "x" },
    { ch = "hemt_5R_Vg2", V = "x" },
    { ch = "hemt_5R_Id", I = "10000 * x" },
]

[spectrometer]
_ = "XFFTS"
host = "localhost"
data_port = 25144
cmd_port = 16210
synctime_us = 100000
bw_MHz = { 1 = 2000, 2 = 2000, 3 = 2000, 4 = 2000, 5 = 2000, 6 = 2000, 7 = 2000, 8 = 2000, 9 = 2000, 10 = 2000, 11 = 2000, 12 = 2000, 13 = 2000, 14 = 2000, 15 = 2000 }
max_ch = 32768

[attenuator.beam2]
_ = "11713B"
communicator = "GPIB"
host = "172.20.0.161"
gpib_port = 28
model = "AG8494g"
channel = { IF2R = "X", IF2L = "Y" }

[attenuator.beam3]
_ = "11713B"
communicator = "LAN"
host = "172.20.0.164"
lan_port = 5025
model = "AG8494g"
channel = { IF3R = "X", IF3L = "Y" }

[attenuator.beam4]
_ = "11713B"
communicator = "LAN"
host = "172.20.0.165"
lan_port = 5025
model = "AG8494g"
channel = { IF4R = "X", IF4L = "Y" }

[attenuator.beam5]
_ = "11713B"
communicator = "LAN"
host = "172.20.0.166"
lan_port = 5025
model = "AG8494g"
channel = { IF5R = "X", IF5L = "Y" }

[attenuator.beam1R]
_ = "11713B"
communicator = "GPIB"
host = "172.20.0.162"
gpib_port = 28
model = "AG8494g"
channel = { IF1RU = "X", IF1RL = "Y" }

[attenuator.beam1L]
_ = "11713B"
communicator = "GPIB"
host = "172.20.0.163"
gpib_port = 28
model = "AG8494g"
channel = { IF1LU = "X", IF1LL = "Y" }

[local_attenuator]
_ = "CPZ340516"
channel = { sis_2L = 1, sis_2R = 2, sis_3L = 3, sis_3R = 4, sis_4L = 5, sis_4R = 6, sis_5L = 7, sis_5R = 8 }
range = "DA0_100mA"
rate = 0.1
rsw_id = 0

[vacuum_gauge]
_ = "TPG261"
communicator = "RS232"
rs232_port = ""
